module.exports = [{
    id: 1,
    name: 'Bulbasaur',
    type: 'Grass',
    form: 'First Form',
},
{
    id: 2,
    name: 'Ivysaur',
    type: 'Grass',
    form: 'Second Form',
}, 
{
    id: 3,
    name: 'Venusaur',
    type: 'Grass, Poison',
    form: 'Final Form',
},
{
    id: 4,
    name: 'Charmander',
    type: 'Fire',
    form: 'First Form',
}, 
{
    id: 5,
    name: 'Charmeleon',
    type: 'Fire',
    form: 'Second Form',
},
{
    id: 6,
    name: 'Charizard',
    type: 'Fire, Flying',
    form: 'Final Form',
}, 
{
    id: 7,
    name: 'Squirtle',
    type: 'Water',
    form: 'First Form',
},
{
    id: 8,
    name: 'Wartortle',
    type: 'Water',
    form: 'Second Form',
},
{
    id: 9,
    name: 'Blastoise',
    type: 'Water',
    form: 'Final Form',
}, 
{
    id: 10,
    name: 'Caterpie',
    type: 'Bug',
    form: 'First Form',
}, 
{
    id: 11,
    name: 'Metapod',
    type: 'Bug',
    form: 'Second Form',
},
{
    id: 12,
    name: 'Butterfree',
    type: 'Bug, Flying',
    form: 'Final Form',
},
{
    id: 13,
    name: 'Weedle',
    type: 'Bug',
    form: 'First Form',
}, 
{
    id: 14,
    name: 'Kakuna',
    type: 'Bug',
    form: 'Second Form',
},
{
    id: 15,
    name: 'Beedrill',
    type: 'Bug, Flying',
    form: 'Final Form',
},
{
    id: 16,
    name: 'Pidgey',
    type: 'Flying',
    form: 'First Form',
}, 
{
    id: 17,
    name: 'Pidgeotto',
    type: 'Flying',
    form: 'Second Form',
}, 
{
    id: 18,
    name: 'Pidgeot',
    type: 'Flying',
    form: 'Final Form',
},
{
    id: 19,
    name: 'Rattata',
    type: 'Normal',
    form: 'First Form',
},
{
    id: 20,
    name: 'Raticate',
    type: 'Normal',
    form: 'Final Form',
}, 
{
    id: 21,
    name: 'Spearow',
    type: 'Flying',
    form: 'First Form',
},
{
    id: 22,
    name: 'Fearow',
    type: 'Flying',
    form: 'Final Form',
},
{
    id: 23,
    name: 'Ekans',
    type: 'Poison',
    form: 'First Form',
},
{
    id: 24,
    name: 'Arbok',
    type: 'Poison',
    form: 'Final Form',
}, 
{
    id: 25,
    name: 'Pikachu',
    type: 'Electric',
    form: 'First Form',
}, 
{
    id: 26,
    name: 'Raichu',
    type: 'Electric',
    form: 'Final Form',
},
{
    id: 27,
    name: 'Sandshrew',
    type: 'Ground',
    form: 'First Form',
},
{
    id: 28,
    name: 'Sandslash',
    type: 'Ground',
    form: 'Final Form',
}, 
{
    id: 29,
    name: 'Nidoran (female)',
    type: 'Poison',
    form: 'First Form',
},
{
    id: 30,
    name: 'Nidorina',
    type: 'Poison',
    form: 'Second Form',
},
{
    id: 31,
    name: 'Nidoqueen',
    type: 'Poison, Ground',
    form: 'Final Form',
},
{
    id: 32,
    name: 'Nidoran (male)',
    type: 'Poison',
    form: 'First Form',
}];
